---
layout: cv
title: Kate Lee's CV
---
# Kate Lee
Accounting Major, 3.98 GPA

<div id="webaddress">
<a href="https://www.linkedin.com/in/kate-lee-889a49295/">My LinkedIn</a>


## Currently

Pursuing an Accounting Major at BYU-Idaho

### Skilled in

Drake Tax software, Structured Query Language, customer service, Microsoft Office (Word, Excel, PowerPoint), and Google Workspace (Docs, Sheets, Slides)


## Education


`September 2022 - now`
__Brigham Young University - Idaho__

## Awards

`September 2022 - Current`
Full Tuition Academic Grant, BYU-Idaho


### Experience

`January 2025 - April 2025`
Tax Intern at Thrive CPA
-  Tax return computation, completed tax returns for individual clients and businesses
- Information organization, organized and clarified data in easy-to-understand files 
- Bookkeeping, completed monthly recording and organizing of the financial transactions of a business 

`April 2024 - September 2024`
Medical Office Intern at Cancer Care Northwest
- Utilized Excel skills to create/format and build an organizational spreadsheet for medical data
- Created and implemented a company system for others to more easily find and sort archived data
- Digitized key information from archived paper documents for easier reference and location purposes

`April 2023 - September 2023`
Nutrition Intern at EatSmart Idaho
- Provided nutrition education at schools and summer camps for grades K-12
- Prepared healthy food demonstrations 
April 2023 - September 2023 
Post Falls, Idaho
- Arranged and taught nutrition and health lessons (Individual course lessons were typically 1-2 hours long) 

`June 2022 - September 2022`
Barista at Starbucks
- Customer service representative
- Cashier and unique drink preparation
- Certified in food safety and food sanitation techniques 



<!-- ### Footer

Last updated: May 2013 -->